### ISSUE TITLE
Document why we use Socrata-HTTP

### ISSUE THREAD

**Issue by mhotan** [socrata-platform/balboa#13]
Document why we use Socrata-HTTP over [Spray](http://spray.io/), [Play Framework](https://www.playframework.com/), or any other [Akka](http://akka.io/) based approach.

**Comment by velvia** [comment]
+1 !!

Michael if you're considering Spray let's talk.  I have at least one major
OSS project that depends on Spray so I can speak about that (and Akka as
well).

On Thu, Jun 4, 2015 at 8:13 AM, Michael Hotan <notifications@github.com>
wrote:

> Balboa HTTP currently uses Socrata HTTP
> <https://github.com/socrata-platform/socrata-http>. While Socrata HTTP is
> actively being worked on it does not really provide anything more then a
> wrapper around Jetty without Akka support. With true Reactive, type-safe
> aspirations in mind, looking at replacing Socrata-http with a project with
> more support like Spray <http://spray.io/> or Play Framework
> <https://www.playframework.com/> in hopes of taking advantages of Akka
> <http://akka.io/>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/socrata-platform/balboa/issues/13>.
>



-- 
Evan Chan   |   Principal Engineer, Socrata     |    @evanfchan
*Socrata <http://www.socrata.com/> *| The Data Experience Company™
*Socrata isn't about worldly success, but about changing the world
successfully. This is why I'm excited to be here.*
*What does Socrata do? <https://www.youtube.com/watch?v=yyz86MlkriQ> *(watch
our 2 min video)

**Comment by coyotebush** [comment]
Or even [Scalatra](http://scalatra.org/) seems comparable.
