### ISSUE TITLE
Standardize Configuration

### ISSUE THREAD

**Issue by mhotan** [socrata-platform/balboa#15]
Different sub projects are using the same configuration.  

* Standardize property names.
* Implement verifiably properties.
* Look at [type-safe config](https://github.com/typesafehub/config)

- [ ]  Update Client libraries

**Comment by mhotan** [comment]
Configuration throughout the project is scattered, some hard coded, no pattern to follow.  We need to atleast have a pattern to for all configuration through out the project.  

IE:  
* Reverse domain name notation. 
* All Project specific configuration is prefixed with "balboa".  
* following balboa classifies the sub project "producer", "consumer", "http", "agent"
* Following the sub project tag is the whatever the configuration key is. IE: "timeout"

**Comment by coyotebush** [comment]
:+1: explicitly passed Typesafe Config would make the client libraries more ergonomic.

**Comment by mhotan** [comment]
The same goes for package naming.
