### ISSUE TITLE
Balboa Kafka Service

### ISSUE THREAD

**Issue by mhotan-s** [socrata-platform/balboa#7]
BUG: 

Starting multiple Balboa Kafka Service instances within Marathon causes consumer registration to fail.  It appears that starting multiple instances of the task given the same consumer group will cause consumer registration with zookeeper to fail.   It appears that both instances are given the same id within the consumer group.

Example Log output for one of the errors:

INFO - [ConsumerFetcherManager-1431715858002] Stopping leader finder thread
INFO - [ConsumerFetcherManager-1431715858002] Stopping all fetchers
INFO - [ConsumerFetcherManager-1431715858002] All connections stopped
INFO - [balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a], Cleared all relevant queues for this fetcher
INFO - [balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a], Cleared the data chunks in all the consumer message iterators
INFO - [balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a], Committing all offsets after clearing the fetcher queues
INFO - [balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a], Releasing partition ownership
INFO - Consumer balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a rebalancing the following partitions: ArrayBuffer(0, 1, 2, 3, 4, 5, 6, 7) for topic metrics.tenant with consumers: List(balboa-kafka-consumer_751103ff7813-1431658461137-26e2ded4-0, balboa-kafka-consumer_751103ff7813-1431658461137-26e2ded4-1, balboa-kafka-consumer_751103ff7813-1431658461137-26e2ded4-2, balboa-kafka-consumer_751103ff7813-1431658461137-26e2ded4-3, balboa-kafka-consumer_751103ff7813-1431658461137-26e2ded4-4, balboa-kafka-consumer_751103ff7813-1431658461137-26e2ded4-5, balboa-kafka-consumer_751103ff7813-1431658461137-26e2ded4-6, balboa-kafka-consumer_751103ff7813-1431658461137-26e2ded4-7, balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-0, balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-1, balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-2, balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-3, balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-4, balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-5, balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-6, balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-7)
WARN - No broker partitions consumed by consumer thread balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-5 for topic metrics.tenant
WARN - No broker partitions consumed by consumer thread balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-6 for topic metrics.tenant
WARN - No broker partitions consumed by consumer thread balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-3 for topic metrics.tenant
WARN - No broker partitions consumed by consumer thread balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-7 for topic metrics.tenant
WARN - No broker partitions consumed by consumer thread balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-1 for topic metrics.tenant
WARN - No broker partitions consumed by consumer thread balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-4 for topic metrics.tenant
WARN - No broker partitions consumed by consumer thread balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-2 for topic metrics.tenant
WARN - No broker partitions consumed by consumer thread balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-0 for topic metrics.tenant
INFO - [balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a], Consumer balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a selected partitions :
INFO - [balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-leader-finder-thread], Starting
INFO - [balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a], end rebalancing consumer balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a try #0
Group class com.socrata.balboa.service.kafka.consumer.BalboaConsumerGroup topic: metrics.tenant number of consumers: 8 data store: com.socrata.balboa.metrics.data.impl.BufferedDataStore@3986d72f created
Completed Creating Consumer Group
Adding Shutdown hook
Starting consumer group
INFO - Starting class com.socrata.balboa.service.kafka.consumer.BalboaConsumerGroup topic: metrics.tenant number of consumers: 8 data store: com.socrata.balboa.metrics.data.impl.BufferedDataStore@3986d72f...
INFO - [balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a], begin rebalancing consumer balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a try #0
INFO - [ConsumerFetcherManager-1431715858002] Stopping leader finder thread
INFO - [balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-leader-finder-thread], Shutting down
INFO - [balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-leader-finder-thread], Stopped
INFO - [balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-leader-finder-thread], Shutdown completed
INFO - [ConsumerFetcherManager-1431715858002] Stopping all fetchers
INFO - [ConsumerFetcherManager-1431715858002] All connections stopped
INFO - [balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a], Cleared all relevant queues for this fetcher
INFO - [balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a], Cleared the data chunks in all the consumer message iterators
INFO - [balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a], Committing all offsets after clearing the fetcher queues
INFO - [balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a], Releasing partition ownership
INFO - [balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a], exception during rebalance
org.I0Itec.zkclient.exception.ZkNoNodeException: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /consumers/balboa-kafka-consumer/ids/balboa-kafka-consumer_751103ff7813-1431658461137-26e2ded4
	at org.I0Itec.zkclient.exception.ZkException.create(ZkException.java:47)
	at org.I0Itec.zkclient.ZkClient.retryUntilConnected(ZkClient.java:685)
	at org.I0Itec.zkclient.ZkClient.readData(ZkClient.java:766)
	at org.I0Itec.zkclient.ZkClient.readData(ZkClient.java:761)
	at kafka.utils.ZkUtils$.readData(ZkUtils.scala:449)
	at kafka.consumer.TopicCount$.constructTopicCount(TopicCount.scala:61)
	at kafka.utils.ZkUtils$$anonfun$getConsumersPerTopic$1.apply(ZkUtils.scala:671)
	at kafka.utils.ZkUtils$$anonfun$getConsumersPerTopic$1.apply(ZkUtils.scala:670)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at kafka.utils.ZkUtils$.getConsumersPerTopic(ZkUtils.scala:670)
	at kafka.consumer.AssignmentContext.<init>(PartitionAssignor.scala:52)
	at kafka.consumer.ZookeeperConsumerConnector$ZKRebalancerListener.kafka$consumer$ZookeeperConsumerConnector$ZKRebalancerListener$$rebalance(ZookeeperConsumerConnector.scala:659)
	at kafka.consumer.ZookeeperConsumerConnector$ZKRebalancerListener$$anonfun$syncedRebalance$1$$anonfun$apply$mcV$sp$1.apply$mcVI$sp(ZookeeperConsumerConnector.scala:608)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:141)
	at kafka.consumer.ZookeeperConsumerConnector$ZKRebalancerListener$$anonfun$syncedRebalance$1.apply$mcV$sp(ZookeeperConsumerConnector.scala:602)
	at kafka.consumer.ZookeeperConsumerConnector$ZKRebalancerListener$$anonfun$syncedRebalance$1.apply(ZookeeperConsumerConnector.scala:599)
	at kafka.consumer.ZookeeperConsumerConnector$ZKRebalancerListener$$anonfun$syncedRebalance$1.apply(ZookeeperConsumerConnector.scala:599)
	at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:33)
	at kafka.consumer.ZookeeperConsumerConnector$ZKRebalancerListener.syncedRebalance(ZookeeperConsumerConnector.scala:598)
	at kafka.consumer.ZookeeperConsumerConnector$ZKRebalancerListener$$anon$1.run(ZookeeperConsumerConnector.scala:551)
Caused by: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /consumers/balboa-kafka-consumer/ids/balboa-kafka-consumer_751103ff7813-1431658461137-26e2ded4
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:111)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:1155)
	at org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:1184)
	at org.I0Itec.zkclient.ZkConnection.readData(ZkConnection.java:103)
	at org.I0Itec.zkclient.ZkClient$9.call(ZkClient.java:770)
	at org.I0Itec.zkclient.ZkClient$9.call(ZkClient.java:766)
	at org.I0Itec.zkclient.ZkClient.retryUntilConnected(ZkClient.java:675)
	... 21 more
INFO - [balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a], end rebalancing consumer balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a try #0
INFO - [balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a], Rebalancing attempt failed. Clearing the cache before the next rebalancing operation is triggered
INFO - [ConsumerFetcherManager-1431715858002] Stopping leader finder thread
INFO - [ConsumerFetcherManager-1431715858002] Stopping all fetchers
INFO - [ConsumerFetcherManager-1431715858002] All connections stopped
INFO - [balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a], Cleared all relevant queues for this fetcher
INFO - [balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a], Cleared the data chunks in all the consumer message iterators
INFO - [balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a], Committing all offsets after clearing the fetcher queues
INFO - [balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a], begin rebalancing consumer balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a try #1
INFO - [ConsumerFetcherManager-1431715858002] Stopping leader finder thread
INFO - [ConsumerFetcherManager-1431715858002] Stopping all fetchers
INFO - [ConsumerFetcherManager-1431715858002] All connections stopped
INFO - [balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a], Cleared all relevant queues for this fetcher
INFO - [balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a], Cleared the data chunks in all the consumer message iterators
INFO - [balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a], Committing all offsets after clearing the fetcher queues
INFO - [balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a], Releasing partition ownership
INFO - Consumer balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a rebalancing the following partitions: ArrayBuffer(0, 1, 2, 3, 4, 5, 6, 7) for topic metrics.tenant with consumers: List(balboa-kafka-consumer_60f1185169c7-1431715868544-626f3fc1-0, balboa-kafka-consumer_60f1185169c7-1431715868544-626f3fc1-1, balboa-kafka-consumer_60f1185169c7-1431715868544-626f3fc1-2, balboa-kafka-consumer_60f1185169c7-1431715868544-626f3fc1-3, balboa-kafka-consumer_60f1185169c7-1431715868544-626f3fc1-4, balboa-kafka-consumer_60f1185169c7-1431715868544-626f3fc1-5, balboa-kafka-consumer_60f1185169c7-1431715868544-626f3fc1-6, balboa-kafka-consumer_60f1185169c7-1431715868544-626f3fc1-7, balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-0, balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-1, balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-2, balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-3, balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-4, balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-5, balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-6, balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-7)
WARN - No broker partitions consumed by consumer thread balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-5 for topic metrics.tenant
WARN - No broker partitions consumed by consumer thread balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-6 for topic metrics.tenant
WARN - No broker partitions consumed by consumer thread balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-3 for topic metrics.tenant
WARN - No broker partitions consumed by consumer thread balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-7 for topic metrics.tenant
WARN - No broker partitions consumed by consumer thread balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-1 for topic metrics.tenant
WARN - No broker partitions consumed by consumer thread balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-4 for topic metrics.tenant
WARN - No broker partitions consumed by consumer thread balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-2 for topic metrics.tenant
WARN - No broker partitions consumed by consumer thread balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-0 for topic metrics.tenant
INFO - [balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a], Consumer balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a selected partitions :
INFO - [balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a], end rebalancing consumer balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a try #1
INFO - [balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a], begin rebalancing consumer balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a try #0
INFO - [balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-leader-finder-thread], Starting
INFO - [ConsumerFetcherManager-1431715858002] Stopping leader finder thread
INFO - [balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-leader-finder-thread], Shutting down
INFO - [balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-leader-finder-thread], Stopped
INFO - [balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-leader-finder-thread], Shutdown completed
INFO - [ConsumerFetcherManager-1431715858002] Stopping all fetchers
INFO - [ConsumerFetcherManager-1431715858002] All connections stopped
INFO - [balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a], Cleared all relevant queues for this fetcher
INFO - [balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a], Cleared the data chunks in all the consumer message iterators
INFO - [balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a], Committing all offsets after clearing the fetcher queues
INFO - [balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a], Releasing partition ownership
INFO - Consumer balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a rebalancing the following partitions: ArrayBuffer(0, 1, 2, 3, 4, 5, 6, 7) for topic metrics.tenant with consumers: List(balboa-kafka-consumer_60f1185169c7-1431715868544-626f3fc1-0, balboa-kafka-consumer_60f1185169c7-1431715868544-626f3fc1-1, balboa-kafka-consumer_60f1185169c7-1431715868544-626f3fc1-2, balboa-kafka-consumer_60f1185169c7-1431715868544-626f3fc1-3, balboa-kafka-consumer_60f1185169c7-1431715868544-626f3fc1-4, balboa-kafka-consumer_60f1185169c7-1431715868544-626f3fc1-5, balboa-kafka-consumer_60f1185169c7-1431715868544-626f3fc1-6, balboa-kafka-consumer_60f1185169c7-1431715868544-626f3fc1-7, balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-0, balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-1, balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-2, balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-3, balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-4, balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-5, balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-6, balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-7)
WARN - No broker partitions consumed by consumer thread balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-5 for topic metrics.tenant
WARN - No broker partitions consumed by consumer thread balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-6 for topic metrics.tenant
WARN - No broker partitions consumed by consumer thread balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-3 for topic metrics.tenant
WARN - No broker partitions consumed by consumer thread balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-7 for topic metrics.tenant
WARN - No broker partitions consumed by consumer thread balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-1 for topic metrics.tenant
WARN - No broker partitions consumed by consumer thread balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-4 for topic metrics.tenant
WARN - No broker partitions consumed by consumer thread balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-2 for topic metrics.tenant
WARN - No broker partitions consumed by consumer thread balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-0 for topic metrics.tenant
INFO - [balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a], Consumer balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a selected partitions :
INFO - [balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a], end rebalancing consumer balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a try #0
INFO - [balboa-kafka-consumer_751f0e3c6d5d-1431715857803-f83a334a-leader-finder-thread], Starting

**Comment by mhotan** [comment]
Turns out to be a Zookeeper client issue.
